import json
import zipfile
import io
from dataclasses import dataclass, asdict
from pathlib import Path

import numpy as np
from scipy import ndimage


@dataclass
class NonDetConfig:
    occ_bin: float = 0.005          # 0.5 percentage-point occupancy bin
    speed_bin: float = 1.0          # 1 mph bin
    min_count: int = 5              # minimum support per (occ, speed) cell
    flow_std_threshold: float = 100.0  # vehicles/5min


@dataclass
class CausalEquivConfig:
    flow_bin: int = 4               # 4 vehicles/5min output band
    occ_bin: float = 0.005          # 0.5 percentage-point occupancy bin
    speed_bin: float = 1.0          # 1 mph bin
    min_samples_per_flow_band: int = 500
    min_cell_count: int = 6         # minimum count for an occupied input cell
    min_component_cells: int = 14   # each disconnected component must have at least this many occupied cells


@dataclass
class ExperimentResult:
    total_samples: int
    non_deterministic_rate: float
    non_deterministic_samples: int
    non_deterministic_groups: int
    causal_equivalence_rate: float
    causal_equivalence_samples: int
    causal_equivalence_flow_bands: int
    config_non_deterministic: dict
    config_causal_equivalence: dict


def load_pems08_from_zip(zip_path: str):
    with zipfile.ZipFile(zip_path, 'r') as zf:
        arr = np.load(io.BytesIO(zf.read('PEMS08/pems08.npz')))['data']
    # Raw channel order in this .npz is [flow, occupancy, speed]
    flow = arr[:, :, 0].reshape(-1).astype(np.float64)
    occ = arr[:, :, 1].reshape(-1).astype(np.float64)
    speed = arr[:, :, 2].reshape(-1).astype(np.float64)
    return flow, occ, speed


def compute_non_deterministic_rate(flow, occ, speed, cfg: NonDetConfig):
    ob = np.floor(occ / cfg.occ_bin).astype(np.int32)
    sb = np.floor(speed / cfg.speed_bin).astype(np.int32)
    key = ob.astype(np.int64) * 100000 + sb.astype(np.int64)

    order = np.argsort(key, kind='mergesort')
    key_s = key[order]
    flow_s = flow[order]

    _, idx, counts = np.unique(key_s, return_index=True, return_counts=True)
    sums = np.add.reduceat(flow_s, idx)
    sums2 = np.add.reduceat(flow_s * flow_s, idx)
    means = sums / counts
    stds = np.sqrt(np.maximum(sums2 / counts - means * means, 0.0))

    ambiguous_groups = (counts >= cfg.min_count) & (stds >= cfg.flow_std_threshold)
    ambiguous_mask_sorted = np.repeat(ambiguous_groups, counts)
    ambiguous_samples = int(ambiguous_mask_sorted.sum())
    ambiguous_rate = ambiguous_samples / len(flow)
    ambiguous_group_count = int(ambiguous_groups.sum())
    return ambiguous_rate, ambiguous_samples, ambiguous_group_count


def compute_causal_equivalence_rate(flow, occ, speed, cfg: CausalEquivConfig):
    # Operational definition:
    # samples are counted as “causal-equivalent” when the SAME output flow band
    # is generated by at least two disconnected dense regions in the (occ, speed)
    # input plane.
    fb = np.floor(flow / cfg.flow_bin).astype(np.int32)
    order = np.argsort(fb, kind='mergesort')
    fb_s = fb[order]
    occ_s = occ[order]
    speed_s = speed[order]

    vals, idx, counts = np.unique(fb_s, return_index=True, return_counts=True)
    structure = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]], dtype=np.int32)

    total_flagged_samples = 0
    flagged_bands = 0

    for start, c, _ in zip(idx, counts, vals):
        if c < cfg.min_samples_per_flow_band:
            continue

        sl = slice(start, start + c)
        ob = np.floor(occ_s[sl] / cfg.occ_bin).astype(np.int32)
        sb = np.floor(speed_s[sl] / cfg.speed_bin).astype(np.int32)
        ob0, sb0 = ob.min(), sb.min()

        hist = np.zeros((ob.max() - ob0 + 1, sb.max() - sb0 + 1), dtype=np.int16)
        np.add.at(hist, (ob - ob0, sb - sb0), 1)

        dense = hist >= cfg.min_cell_count
        labeled, n_components = ndimage.label(dense, structure=structure)
        if n_components < 2:
            continue

        component_sizes = np.bincount(labeled.ravel())[1:]  # drop background
        n_large_components = int((component_sizes >= cfg.min_component_cells).sum())
        if n_large_components >= 2:
            flagged_bands += 1
            total_flagged_samples += int(c)

    flagged_rate = total_flagged_samples / len(flow)
    return flagged_rate, total_flagged_samples, flagged_bands


def main():
    zip_path = '.../data/PEMS08.zip'
    flow, occ, speed = load_pems08_from_zip(zip_path)

    nd_cfg = NonDetConfig()
    ce_cfg = CausalEquivConfig()

    nd_rate, nd_samples, nd_groups = compute_non_deterministic_rate(flow, occ, speed, nd_cfg)
    ce_rate, ce_samples, ce_bands = compute_causal_equivalence_rate(flow, occ, speed, ce_cfg)

    result = ExperimentResult(
        total_samples=len(flow),
        non_deterministic_rate=nd_rate,
        non_deterministic_samples=nd_samples,
        non_deterministic_groups=nd_groups,
        causal_equivalence_rate=ce_rate,
        causal_equivalence_samples=ce_samples,
        causal_equivalence_flow_bands=ce_bands,
        config_non_deterministic=asdict(nd_cfg),
        config_causal_equivalence=asdict(ce_cfg),
    )

    out_json = Path('/mnt/data/pems08_reproduction_results.json')
    out_json.write_text(json.dumps(asdict(result), indent=2), encoding='utf-8')

    report = f'''

## Data
- File: `PEMS08.zip`
- Raw tensor shape: `(17856, 170, 3)`
- Flattened samples used in this experiment: `{len(flow):,}`
- Channel interpretation inferred: `[flow, occupancy, speed]`

## Goal
1. **Non-deterministic mapping**: nearly identical `(occupancy, speed)` inputs produce highly variable `flow`.
2. **Causal equivalence**: the same `flow` band is generated by multiple disconnected dense regions in the `(occupancy, speed)` plane.

## Operational definition A: non-deterministic mapping
- Occupancy is binned with width `{nd_cfg.occ_bin}`.
- Speed is binned with width `{nd_cfg.speed_bin}` mph.
- A cell is counted only if it has at least `{nd_cfg.min_count}` samples.
- A cell is marked ambiguous if the within-cell flow standard deviation is at least `{nd_cfg.flow_std_threshold}` vehicles/5min.

### Result
- Ambiguous samples: `{nd_samples:,}` / `{len(flow):,}`
- Rate: `{nd_rate * 100:.3f}%`

## Operational definition B: causal equivalence
- Flow is grouped into bands of width `{ce_cfg.flow_bin}` vehicles/5min.
- Within each flow band, the `(occupancy, speed)` plane is binned by `{ce_cfg.occ_bin}` occupancy and `{ce_cfg.speed_bin}` mph.
- A cell is kept only if it contains at least `{ce_cfg.min_cell_count}` samples.
- A flow band is marked “causal-equivalent” if it contains at least **two disconnected dense components**, and each component has at least `{ce_cfg.min_component_cells}` occupied cells.
- Only flow bands with at least `{ce_cfg.min_samples_per_flow_band}` samples are evaluated.

### Result
- Flagged samples: `{ce_samples:,}` / `{len(flow):,}`
- Rate: `{ce_rate * 100:.3f}%`

'''
    Path('/mnt/data/PEMS08_reproducibility_report.md').write_text(report, encoding='utf-8')
    print(report)
    print(f'JSON saved to: {out_json}')


if __name__ == '__main__':
    main()
